site_name: EduCore Documentation

site_description: Documentation as Code project for EduCore platform

nav:
  - Home: index.md
  - Architecture:
      - SSD: architecture/SSD.md
      - SDD: architecture/SDD.md
      - ISD: architecture/ISD.md
  - Quality:
      - Test Strategy: quality/test-strategy.md
      - Traceability Matrix: quality/traceability-matrix.md
  - Developer:
      - Onboarding: developer/onboarding.md

theme:
  name: material